remote_theme: coursweb/jk-theme
title: Développement d’interfaces 2 – CSS
description: Un cours sur le développement web.
lang: fr-FR
markdown: GFM
# Chapters : top navigation
chapters:
 - title: Teams
   url: https://teams.microsoft.com/l/channel/19%3af0dbe85c7fa84b01b9831dd3b3855843%40thread.tacv2/Dev%25202%2520(CSS)?groupId=cddcd5ea-659b-4e31-bd8b-2d0781a09f8b&tenantId=906ab908-04f9-4a80-ba9c-875a36e77bc1

# Footer content
# Content is split in three columns.   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2017–2021</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/eracom-id301/cours-dev2-css">Lien Github</a></li></ul>
footer_col_3: Un cours sur le développement web.