remote_theme: coursweb/jk-theme
title: Développement d'interfaces 2
description: Cours développement d'interfaces 2.
lang: fr-FR
# markdown: GFM
robots: noindex, nofollow
# menu 
chapters:
 - title: 💻 Cours Dev 2
   url: https://eracom-id301.github.io/cours-dev2-css/
 - title: 💎 Cours Projet Interface
   url: https://eracom-id301.github.io/cours-projet-interface/
 - title: Référence CSS
   url: https://cours-web.ch/css/
# - title: Infos IMD
#   url: https://eracom.ch/informations-eleves-id/
# - title: Plan de formation
#   url: https://code.eracom-pedagogique.ch/formation-imd-2020/   
# - title: Fontes IMD
#   url: https://code.eracom-pedagogique.ch/fontes-imd/  
 - title: 🏀 Teams
   url: https://teams.microsoft.com/l/team/19%3a5J-kUQLWobtr3jWyD3ZyOIe2QJLUREDwBk6s3aiw79k1%40thread.tacv2/conversations?groupId=c6d65cb0-98f3-4828-9f13-3cf6f5fa0cf5&tenantId=906ab908-04f9-4a80-ba9c-875a36e77bc1
 - title: 🧠 Podsie
   url: https://student.podsie.org/
# pied de page   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2017-2021</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/eracom-id301/cours-dev2-css">Lien Github</a></li></ul>
