remote_theme: coursweb/jk-theme
title: Infos IMD
description: Un cours CSS.
lang: fr-FR
markdown: GFM
chapters:
 - title: Cours CSS
   url: https://cours-web.ch/css/
footer_col_1:
footer_col_2:
footer_col_3:
