remote_theme: coursweb/jk-theme
title: Infos IMD
description: Cours développement d'interfaces 2.
lang: fr-FR
markdown: GFM
chapters:
 - title: Cours CSS
   url: https://cours-web.ch/css/
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2017-2021</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/eracom-id301/cours-dev2-css">Lien Github</a></li></ul>
footer_col_3: Un cours CSS.
